# Generated by Django 2.0 on 2020-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
