# Generated by Django 2.0 on 2020-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0002_order_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='another_document',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
