# Generated by Django 2.0 on 2020-07-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0005_auto_20200726_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
