# Generated by Django 2.0 on 2020-07-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0006_auto_20200726_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
