# Generated by Django 2.0 on 2020-07-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0008_auto_20200726_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='passport',
        ),
    ]
