# Generated by Django 2.0 on 2020-07-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0009_remove_client_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
