# Generated by Django 2.0 on 2020-07-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0010_client_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_client',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.SET_DEFAULT, to='work_app.Client'),
        ),
    ]
