# Generated by Django 2.0 on 2020-07-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0011_auto_20200727_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('recommended_minimum', models.IntegerField(blank=True, default=0)),
                ('current_amount', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('recommended_minimum', models.IntegerField(blank=True, default=0)),
                ('current_amount', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
