# Generated by Django 2.0 on 2020-07-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0012_baritem_consumables'),
    ]

    operations = [
        migrations.AddField(
            model_name='baritem',
            name='uni',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='consumables',
            name='uni',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
