# Generated by Django 2.0 on 2020-07-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0013_auto_20200728_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baritem',
            old_name='uni',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='consumables',
            old_name='uni',
            new_name='unit',
        ),
    ]
